name: magni_investing
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  google_fonts:
  fluttericon:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito:
  faker:
  effective_dart:
  flutter_launcher_icons:
  animated_splash_screen:
  page_transition: 

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/welcome/
    - lib/assets/images/Logo/
    - lib/assets/images/logo_icon/


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/app_icon.png"